export const tasks: TaskItem[] = [
  {
    id: "1",
    title: "Morning jog",
    description: "Go for a 30-minute jog around the park.",
    timeRange: "6:00 AM - 6:30 AM",
    category: "personal",
    completed: true,
  },
  {
    id: "2",
    title: "Team meeting",
    description: "Discuss project progress and upcoming tasks.",
    timeRange: "10:00 AM - 11:00 AM",
    category: "work",
    completed: false,
  },
  {
    id: "3",
    title: "Grocery shopping",
    description: "Buy vegetables, fruits, and household supplies.",
    timeRange: "5:00 PM - 6:00 PM",
    category: "personal",
    completed: false,
  },
  {
    id: "4",
    title: "Code review",
    description: "Review pull requests for the new feature branch.",
    timeRange: "3:00 PM - 4:00 PM",
    category: "work",
    completed: true,
  },
  {
    id: "5",
    title: "Yoga session",
    description: "Attend a one-hour yoga class at the studio.",
    timeRange: "7:00 AM - 8:00 AM",
    category: "personal",
    completed: false,
  },
  {
    id: "6",
    title: "Prepare presentation",
    description: "Create slides for the client meeting.",
    timeRange: "2:00 PM - 3:00 PM",
    category: "work",
    completed: false,
  },
  {
    id: "7",
    title: "Doctor's appointment",
    description: "Annual health check-up at the clinic.",
    timeRange: "9:00 AM - 9:30 AM",
    category: "personal",
    completed: true,
  },
  {
    id: "8",
    title: "Client call",
    description: "Discuss project deliverables with the client.",
    timeRange: "4:00 PM - 5:00 PM",
    category: "work",
    completed: false,
  },
  {
    id: "9",
    title: "Evening walk",
    description: "Relaxing walk in the park before dinner.",
    timeRange: "6:30 PM - 7:00 PM",
    category: "personal",
    completed: false,
  },
  {
    id: "10",
    title: "Update resume",
    description: "Add recent projects and achievements to the resume.",
    timeRange: "8:00 PM - 9:00 PM",
    category: "completed",
    completed: true,
  },
  {
    id: "11",
    title: "Plan weekend trip",
    description: "Decide on location and create an itinerary.",
    timeRange: "7:00 PM - 8:00 PM",
    category: "personal",
    completed: false,
  },
  {
    id: "12",
    title: "Read a book",
    description: "Finish reading the last chapter of the novel.",
    timeRange: "9:30 PM - 10:00 PM",
    category: "personal",
    completed: false,
  },
  {
    id: "13",
    title: "Send progress report",
    description: "Email the weekly progress report to the manager.",
    timeRange: "11:00 AM - 11:15 AM",
    category: "completed",
    completed: true,
  },
  {
    id: "14",
    title: "Brainstorm ideas",
    description: "Work on creative ideas for the marketing campaign.",
    timeRange: "1:00 PM - 2:00 PM",
    category: "work",
    completed: false,
  },
  {
    id: "15",
    title: "Clean the house",
    description: "Vacuum, dust, and organize the living area.",
    timeRange: "3:00 PM - 4:00 PM",
    category: "personal",
    completed: true,
  },
  {
    id: "16",
    title: "Prepare dinner",
    description: "Cook pasta and a side salad for dinner.",
    timeRange: "6:00 PM - 7:00 PM",
    category: "personal",
    completed: false,
  },
  {
    id: "17",
    title: "Write blog post",
    description: "Draft a post about recent trends in web development.",
    timeRange: "8:00 PM - 9:30 PM",
    category: "work",
    completed: false,
  },
  {
    id: "18",
    title: "Organize emails",
    description: "Sort and archive old emails.",
    timeRange: "9:00 AM - 9:30 AM",
    category: "personal",
    completed: true,
  },
  {
    id: "19",
    title: "Workout session",
    description: "Follow a 45-minute HIIT routine.",
    timeRange: "6:30 AM - 7:15 AM",
    category: "personal",
    completed: false,
  },
  {
    id: "20",
    title: "Fix website bug",
    description: "Debug and resolve the API issue on the website.",
    timeRange: "2:30 PM - 3:30 PM",
    category: "work",
    completed: false,
  },
];
