import BorderAsIcon from "../common/components/shared/border-as-icon";


// Define task categories
export const taskCategories: taskCategory[] = [
  { id: "personal", label: "Personal", icon: <BorderAsIcon borderColor={"#000000"} /> },
  { id: "work", label: "Work", icon: <BorderAsIcon borderColor={"#000000"} /> },
  { id: "health", label: "Health", icon: <BorderAsIcon borderColor={"#000000"} /> },
  { id: "completed", label: "Completed", icon: <BorderAsIcon borderColor={"#000000"} /> },
];

// Array of tasks
export const tasks: TaskItem[] = [
  {
    task_id: "1",
    title: "Morning jog",
    description: "Go for a 30-minute jog around the park.",
    dueDate: "2024-12-11",
    timeRange: "6:00 AM - 6:30 AM",
    category: taskCategories[0],
    completed: true,
    type: "list",
  },
  {
    task_id: "2",
    title: "Team meeting",
    description: "Discuss project progress and upcoming tasks.",
    dueDate: "2024-12-11",
    timeRange: "10:00 AM - 11:00 AM",
    category: taskCategories[1],
    completed: false,
    type: "group",
  },
  {
    task_id: "3",
    title: "Grocery shopping",
    description: "Buy vegetables, fruits, and household supplies.",
    dueDate: "2024-12-11",
    timeRange: "5:00 PM - 6:00 PM",
    category: taskCategories[0],
    completed: false,
    type: "list",
  },
  {
    task_id: "4",
    title: "Code review",
    description: "Review pull requests for the new feature branch.",
    dueDate: "2024-12-11",
    timeRange: "3:00 PM - 4:00 PM",
    category: taskCategories[1],
    completed: true,
    type: "list",
  },
  {
    task_id: "5",
    title: "Yoga session",
    dueDate: "2024-12-11",
    timeRange: "7:00 AM - 8:00 AM",
    category: taskCategories[2],
    completed: false,
    type: "list",
  },
  {
    task_id: "6",
    title: "Prepare presentation",
    description: "Create slides for the client meeting.",
    dueDate: "2024-12-12",
    timeRange: "2:00 PM - 3:00 PM",
    category: taskCategories[1],
    completed: false,
    type: "list",
  },
  {
    task_id: "7",
    title: "Doctor's appointment",
    description: "Annual health check-up at the clinic.",
    dueDate: "2024-12-12",
    timeRange: "9:00 AM - 9:30 AM",
    category: taskCategories[2],
    completed: true,
    type: "list",
  },
  {
    task_id: "8",
    title: "Client call",
    description: "Discuss project deliverables with the client.",
    dueDate: "2024-12-13",
    timeRange: "4:00 PM - 5:00 PM",
    category: taskCategories[1],
    completed: false,
    type: "group",
  },
  {
    task_id: "9",
    title: "Evening walk",
    description: "Relaxing walk in the park before dinner.",
    dueDate: "2024-12-13",
    timeRange: "6:30 PM - 7:00 PM",
    category: taskCategories[0],
    completed: false,
    type: "list",
  },
  {
    task_id: "10",
    title: "Update resume",
    description: "Add recent projects and achievements to the resume.",
    dueDate: "2024-12-13",
    timeRange: "8:00 PM - 9:00 PM",
    category: taskCategories[3],
    completed: true,
    type: "list",
  },
  {
    task_id: "11",
    title: "Plan weekend trip",
    description: "Decide on location and create an itinerary.",
    dueDate: "2024-12-14",
    timeRange: "7:00 PM - 8:00 PM",
    category: taskCategories[0],
    completed: false,
    type: "group",
  },
  {
    task_id: "12",
    title: "Read a book",
    description: "Finish reading the last chapter of the novel.",
    dueDate: "2024-12-14",
    timeRange: "9:30 PM - 10:00 PM",
    category: taskCategories[0],
    completed: false,
    type: "list",
  },
  {
    task_id: "13",
    title: "Send progress report",
    description: "Email the weekly progress report to the manager.",
    dueDate: "2024-12-14",
    timeRange: "11:00 AM - 11:15 AM",
    category: taskCategories[3],
    completed: true,
    type: "list",
  },
  {
    task_id: "14",
    title: "Brainstorm ideas",
    description: "Work on creative ideas for the marketing campaign.",
    dueDate: "2024-12-15",
    timeRange: "1:00 PM - 2:00 PM",
    category: taskCategories[1],
    completed: false,
    type: "group",
  },
  {
    task_id: "15",
    title: "Clean the house",
    description: "Vacuum, dust, and organize the living area.",
    dueDate: "2024-12-15",
    timeRange: "3:00 PM - 4:00 PM",
    category: taskCategories[0],
    completed: true,
    type: "list",
  },
  {
    task_id: "16",
    title: "Prepare dinner",
    description: "Cook pasta and a side salad for dinner.",
    dueDate: "2024-12-15",
    timeRange: "6:00 PM - 7:00 PM",
    category: taskCategories[0],
    completed: false,
    type: "list",
  },
  {
    task_id: "17",
    title: "Write blog post",
    description: "Draft a post about recent trends in web development.",
    dueDate: "2024-12-16",
    timeRange: "8:00 PM - 9:30 PM",
    category: taskCategories[1],
    completed: false,
    type: "list",
  },
  {
    task_id: "18",
    title: "Organize emails",
    description: "Sort and archive old emails.",
    dueDate: "2024-12-16",
    timeRange: "9:00 AM - 9:30 AM",
    category: taskCategories[0],
    completed: true,
    type: "list",
  },
  {
    task_id: "19",
    title: "Workout session",
    description: "Follow a 45-minute HIIT routine.",
    dueDate: "2024-12-17",
    timeRange: "6:30 AM - 7:15 AM",
    category: taskCategories[2],
    completed: false,
    type: "list",
  },
  {
    task_id: "20",
    title: "Fix website bug",
    description: "Debug and resolve the API issue on the website.",
    dueDate: "2024-12-17",
    timeRange: "2:30 PM - 3:30 PM",
    category: taskCategories[1],
    completed: false,
    type: "list",
  },
];
